
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ajk0421
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Portfolio_1_development


test:
  <<: *default
  database: Portfolio_1_test


production:
  <<: *default
  database: Portfolio_1_production
  username: Portfolio_1
  password: <%= ENV['PORTFOLIO_1_DATABASE_PASSWORD'] %>
